rails/peter/config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'resume', :to => 'home#resume'
  get 'details', :to => 'home#detail'
  get 'contact', :to => 'home#contact'
  post 'donate', :to => 'home#donate'

  get 'home/index'
  get 'home/resume'
  get 'home/resume/print', :to => 'home#print'
  get 'home/detail'


  resources :projects do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/peter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/peter/app/models/project.rb
class Project < ApplicationRecord

    has_and_belongs_to_many :teches
    has_many_attached :image
    has_one_attached :main_image
end

rails/peter/app/models/tech.rb
class Tech < ApplicationRecord

    has_and_belongs_to_many :projects

end

rails/peter/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

rails/peter/app/controllers/access_controller.rb
class AccessController < ApplicationController
  def menu
    projects = Project.all
    redirect_to project_path(projects[0])
  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        auth_user = found_user.authenticate(params[:password])
      end
    end

    if auth_user

      session[:user_id] = auth_user.id
      redirect_to projects_path()

    else
      flash.now[:notice] = "Invalid username/password"
      render('login')
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'Logged Out'
    redirect_to access_menu_path
  end
end

rails/peter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/peter/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = Project.all
  end

  def resume
    respond_to  do |format|
      format.html
      format.pdf do
        render pdf: 'test',
          template: 'home/print.html.erb',
          layout: 'resume.html.erb',
          page_size: 'letter',
          margin: {top: 15,
                  bottom: 7,
                  left: 10,
                  right: 10},
          outline: {outline: true,
                    outline_depth: 2}
        end
     end
  end

  def detail
    @projects = Project.all
    if params[:id]
      @selected = Project.find(params[:id])
    end
  end

  def contact
  end

  def donate

    Stripe.api_key = Rails.application.credentials.dig(:stripe, :sand_sec_key)

    token = params[:stripeToken]
    first = params[:firstname]
    last = params[:lastname]
    company = params[:company]
    email = params[:email]
    dollars = params[:amount].to_f
    cents = (dollars * 100).ceil.to_i
    begin
      charge = Stripe::Charge.create({
          amount: cents,
          currency: 'usd',
          description: '4 the Kids Donation',
          source: token,
          metadata: {
            'firstname' => first,
            'lastname' => last,
            'company' => company,
            'email' => email
          }
      })
    rescue Stripe::CardError => e
      # Since it's a decline, Stripe::CardError will be caught
      body = e.json_body
      err  = body[:error]
    
      puts "Status is: #{e.http_status}"
      puts "Type is: #{err[:type]}"
      puts "Charge ID is: #{err[:charge]}"
      # The following fields are optional
      puts "Code is: #{err[:code]}" if err[:code]
      puts "Decline code is: #{err[:decline_code]}" if err[:decline_code]
      puts "Param is: #{err[:param]}" if err[:param]
      puts "Message is: #{err[:message]}" if err[:message]
      flash[:alert] = "Sorry, #{err[:message]}"
    rescue Stripe::RateLimitError => e
      # Too many requests made to the API too quickly
      flash[:alert] = "This is emberasing, something went wrong on my end. Please wait just a minute and try again."
    rescue Stripe::InvalidRequestError => e
      # Invalid parameters were supplied to Stripe's API
      flash[:alert] = "Something about that card information didnt match. Give it another try."
    rescue Stripe::AuthenticationError => e
      # Authentication with Stripe's API failed
      # (maybe you changed API keys recently)
      flash[:alert] = "My bad. Something went wrong on my end. You havent been charged. I've been notified. If you provided your email, Ill let you know when its fixed and if your still interested could try donating again."
    rescue Stripe::APIConnectionError => e
      # Network communication with Stripe failed
      flash[:alert] = "My bad. Something went wrong on my end. You havent been charged. I've been notified. If you provided your email, Ill let you know when its fixed and if your still interested could try donating again."
    rescue Stripe::StripeError => e
      # Display a very generic error to the user, and maybe send
      # yourself an email
      flash[:alert] = "My bad. Something went wrong on my end. You havent been charged. I've been notified. If you provided your email, Ill let you know when its fixed and if your still interested could try donating again."
    rescue => e
      # Something else happened, completely unrelated to Stripe
      flash[:alert] = "My bad. Something went wrong on my end. You havent been charged. I've been notified. If you provided your email, Ill let you know when its fixed and if your still interested could try donating again."
    else
      flash[:success] = " #{first} You Are Awesome! Thank you for your donation!"

      contrib = {to: email, amount: dollars, company: company, first: first, last: last}
      DonationMailer.with(contrib: contrib).send_wupty_email.deliver_later

    ensure
      redirect_to home_index_path()
    end

  end
end

rails/peter/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :confirm_logged_in, :only => [:create, :update, :destroy]

  def index
    @projects = Project.all
    redirect_to project_path(@projects[0].id)
  end

  def show
    @user = User.find(session[:user_id]) if session[:user_id]
    @allProjects = Project.all
    @project = Project.find(params[:id])
    @images = @project.image
  end

  def new
    @project = Project.new()
  end

  def create
    project = Project.create!(project_params)

    flash[:notice] = "#{project.title} was created successfully."
    redirect_to(projects_path())

  end

  def edit
    @project = Project.find(params[:id])
    @from = params[:from]
  end

  def update
    @project = Project.find(params[:id])
    # if params[:main_image] != nil
    #   @project.main_image.purge
    #   @project.main_image.attach(params[:main_image])
    # end
    

    # @project.image.attach(params[:image])
    if @project.update_attributes(project_params)
      
      flash[:notice] = "#{@project.title} was updated successfully."
      redirect_to(project_path(@project))

    else
      render('edit')
    end
  end

  def delete
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    flash[:notice] = "#{@project.title} was deleted successfully."
    flash[:success] = true
    redirect_to(projects_path())
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :publicUrl, :adminUrl, :gitUrl, :intro, :main_image, image: [], :tech_ids => [])
  end

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = 'You didnt think that Id let you change things did you? I just left it open for you to see my VERY simple, mostly unnecessary backend system as another entry in my portfolio.'
      redirect_to project_path(params[:id])
    end
  end
end

rails/peter/app/helpers/access_helper.rb
module AccessHelper
end

rails/peter/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/peter/app/helpers/home_helper.rb
module HomeHelper
end

rails/peter/app/helpers/projects_helper.rb
module ProjectsHelper
end

rails/peter/app/views/access/login.html.erb
<div class="login">

    <%= form_tag(access_attempt_login_path, :methos => :post) do %>
    <table>

    <tr>
        <td><%= label_tag(:username) %></td>
        <td><%= text_field_tag(:username, params[:username]) %></td>
    </tr>
    <tr>
        <td><%= label_tag(:password) %></td>
        <td><%= password_field_tag(:password) %></td>
    </tr>
        <td>&nbsp;</td>
        <td><%= submit_tag("Log In") %></td>
        </tr>
    </table>
    <% end %>
</div>

rails/peter/app/views/access/menu.html.erb
<h1>Access#menu</h1>
<p>Find me in app/views/access/menu.html.erb</p>

rails/peter/app/views/home/contact.html.erb
<h1>Send Peter an email</h1>

<%= form_tag('/home/send_email') do -%>
    <%= label_tag 'name', 'Name'%>
    <%= text_field_tag 'name'%><br />
    <%= label_tag 'email', 'Return Email'%>
    <%= text_field_tag 'email'%><br />
    <%= label_tag 'message', 'Message'%>
    <%= text_area_tag 'message'%>
  <div><%= submit_tag 'Save' %></div>
<% end -%>

rails/peter/app/views/home/detail.html.erb
<div class="quick head">Projects</div>
<div class="projects-detail">
    <% @projects.each do |p| %>
        <div id="experience" class="category <%= "selected" if @selected && p.id == @selected.id %>">
            <h2 class="quick"><%= p.title %></h2>
            <p class="intro"><%= p.intro %></p>
            <div class="category-item">
                <ul>
                    <li><%= p.description %></li>
                    <% if p.publicUrl != "" %>
                        <li><%= link_to('View', p.publicUrl, class: "link")  %></li>
                    <% end %>
                    <% if p.publicUrl != "" %>
                        <li><%= link_to('Admin Demo', p.adminUrl, class: "link")  %></li>
                    <% end %>
                    <% if p.publicUrl != "" %>
                        <li><%= link_to('Github', p.gitUrl, class: "link")  %></li>
                    <% end %>
                    <% if p.main_image.attached? %>
                        <li><%= image_tag(p.main_image, class: "project-image") %></li>
                    <% end %>
                    <li>
                        <% for i in 0...p.teches.count %>
                            <% if i < p.teches.count-1 %>
                                <%= "#{p.teches[i].name}," %>
                            <% else %>
                                <%= p.teches[i].name %>
                            <% end %>
                        <% end %>
                    </li>
                </ul>
            </div>
        </div>
    <% end %>
    <div class="view-project-image">
        <div class="image-close"><span class="close-x">X</span></div>
        <div class="image-object-box">
            <div class="image-obj"></div>
        </div>
    </div>
</div>

rails/peter/app/views/home/index.html.erb
<div class="contacts">
    <div class="contact"><a href="http://www.linkedin.com/in/peter-koruga">LinkedIn</a></div>
    <div class="contact"><a href="https://github.com/petek157">Github</a></div>
    <div class="contact"><a href="https://stackoverflow.com/story/peter-koruga">Stackoverflow</a></div>
    <div class="contact"><a href="tel:+1-906-364-8851">Call <span class="twilio-power">Powered by Twilio</span></a></div>
    <div class="contact"><a href="mailto:peterk3@koruga.com?Subject=Portfolio%20Interest">Email</a></div>
</div>
<div class="quick head">Welcome</div>
<div class="home">
    <div id="home-quick" class="category">
        <h2 class="quick">Quick Info</h2>
        <div class="category-item">
            <ul>
                <li>Uniquely expirenced in business for a developer<br />(Employee, Manager, Owner)</li>
                <li>8 and counting live projects</li>
                <li>Numerous more in house projects used in private businesses</li> 
                <li>HTML, CSS, Javascript, jQuery, Swift, Objective-C, AWS, PHP, Ruby, Rails, React, C++ (Wiring), Python, SQL</li>
                <li>16 Certificates from Lynda/LinkedIn Learning</li>
                <li>WILL NEVER STOP LEARNING</li>
                <li>Bachelors of Science NMU 2005</li>
            </ul>
        </div>
    </div>
    <div id="home-projects" class="category">
        <h2 class="quick">Projects</h2>
        <div class="projects">
            <% @projects.each do |p| %>
                <div class="category-item" data-item="<%= p.id%>">
                    <h3 class="intro"><%= p.title %></h3>
                    <ul>
                        <li class="intro"><%= p.intro %></li>
                        <li class="intro">
                            <% for i in 0...p.teches.count %>
                                <% if i < p.teches.count-1 %>
                                    <%= "#{p.teches[i].name}," %>
                                <% else %>
                                    <%= p.teches[i].name %>
                                <% end %>
                            <% end %>
                        </li>
                        <% if p.main_image.attached? %>
                            <li class="intro"><%= image_tag(p.main_image, class: "project-image") %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
    </div>
    </div>
</div>

rails/peter/app/views/home/resume.html.erb
<div class="quick head"><%= link_to(fa_icon("file"), resume_path(format: :pdf)) %><span class="res-space">Resume</span><%= link_to(fa_icon("share"), resume_path(format: :pdf)) %></div>
<div class="resume">
    <div id="experience" class="category">
        <h2 class="quick">Experience</h2>
        <div class="category-item">
            <h3>Indianhead Valley Condos Fullstack</h3>
            <p class="intro">Online availability and booking on the front end and all of the RMS functionality in the back end. The app uses Parseplatform API and Server for data storage and user admin (currently refactoring to use AWS). It is capable of managing all aspects of a family owned lodging facility. Which includes creating, reading, updating and deleting guests, reservations, payments and other financial/bookkeeping/sales data. Payment processing via the Stripe API. Visual reservation calendar for 13 units.</p>
        </div>
        <div class="category-item">
            <h3>Indianhead Valley Condos iOS Admin App</h3>
            <p class="intro">All of the functionality of the back end of the website including Stripe payments.</p>
        </div>
        <div class="category-item">
            <h3>iOS Apps</h3>
            <ul>
                <li>Crime Scene Evidence Marker (Tableview manipulation and Location Service)</li>
                <li>Simple Schedule Viewer (EventKit)</li>
                <li>Crime Scene Identifier Card </li>
                <li>Blood Spatter Angle Calculator</li>
                <li>Blood Spatter Angle Calculator Pro (CloudKit)</li>
            </ul>
        </div>
        <div class="category-item">
            <h3>IoT Projects</h3>
            <p class="intro">IoT projects have become my fun little hobby. Yet they still lend to my knowledge of developing and technology.  Most of the projects have either a companion iOS app or a web app to control them. The newest challenge was designing and etching a homebuilt custom PCB.</p>
            <ul>
                <li>Indianhead Valley Condos temperature sensors and lighting control and app</li>
                <li>Electric line voltage smart thermostat and app</li>
                <li>Turtle tank lighting and heat controller</li>
                <li>Wifi garage door opener and app (Custom PCB)</li>
            </ul>
        </div>
    </div>
    <div id="languages" class="category">
        <h2 class="quick">Languages - Frameworks - Systems</h2>
        <p class="intro">Builing all of these project myself has pushed me to learn a number of different languages to complete the projects.</p>
        <ul class="lang-small">
            <li>HTML</li>
            <li>CSS</li>
            <li>Javascript</li>
            <li>JQuery</li>
            <li>Swift</li>
            <li>Objective-C</li>
            <li>PHP</li>
            <li>Ruby</li>
            <li>Rails</li>
            <li>React</li>
            <li>C++ (Wiring)</li>
            <li>Python</li>
            <li>SQL</li>
            <li>AWS</li>
        </ul>
        <div class="lang-large">
            <div>HTML</div>
            <div>CSS</div>
            <div>Javascript</div>
            <div>JQuery</div>
            <div>Swift</div>
            <div>Objective-C</div>
            <div>PHP</div>
            <div>Ruby</div>
            <div>Rails</div>
            <div>React</div>
            <div>C++ (Wiring)</div>
            <div>Python</div>
            <div>SQL</div>
            <div>AWS</div>
        </div>
    </div>
    <div id="certificates" class="category">
        <h2 class="quick">Certificates from Lynda.com and LinkedIn</h2>
        <ul>
            <li>Learning React.js</li><li>Learning Server-Side Swift with Vapor</li><li>Accounting Foundations: Bookkeeping</li><li>Learning Video Production and Editing</li><li>Finance Essentials for Small Business</li><li>Accounting Foundations</li><li>Bootstrap 3 Essential Training</li><li>jQuery Essential Training</li><li>Validating and Processing Forms with Javascript and PHP</li><li>InDesign CS5: Print Production Guidelines</li><li>Swift Essential Training</li><li>Distributing iOS Applications Through the App Store</li><li>Learning Python</li><li>SQL Essential Training</li>
        </ul>
    </div>
    <div id="education" class="category">
        <h2 class="quick">Education</h2>
        <div class="category-item">
            <p class="intro">Bachelors of Science in Business from Northern Michigan University 2005</p>
        </div>
    </div>
</div>

rails/peter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="admin">
    
    <div id="note"><!-- Make success error dynamic-->
      <% if !flash[:notice].blank? %>
          <div class="success">
              <%= flash[:notice] %>
          </div>
      <% else %>
          <div class="divider">
              
          </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

rails/peter/app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peter Koruga</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>

    <% if !flash[:notice].blank? %>
        <div class=" note notice">
            <%= flash[:notice] %>
        </div>
    <% elsif flash[:success] %>
        <div class="note success">
            <%= flash[:success] %>
        </div>
    <% elsif flash[:alert] %>
        <div class="note alert">
            <%= flash[:alert] %>
        </div>
    <% end %>
    <!--<div class="stripe"><img src="/donate.png"/></div>-->
    
    <div class="nav">
        
        <div class="nav-left">
            <div class="name"><%= link_to('Peter Koruga', root_path()) %></div>
        </div>
        <div class="nav-right">
            <ul>
                <li><%= link_to('Projects', details_path()) %></li>
                <li><%= link_to('Resume', resume_path()) %></li>
                <li class="stripe">Donate to 4 the Kids</li>
            </ul>
        </div>
        <!--<div class="stripe">Donate to 4 the Kids</div>-->
        <div class="nav-contact">
            <ul>
              <li class="contact"><%= link_to(fa_icon("linkedin"), "http://www.linkedin.com/in/peter-koruga") %></li>
              <li class="contact"><%= link_to(fa_icon("github"), "https://github.com/petek157") %></li>
              <li class="contact"><%= link_to(fa_icon("stack-overflow"), "https://stackoverflow.com/story/peter-koruga") %></li>
              <li class="contact"><%= link_to(fa_icon("envelope"), "mailto:peterk3@koruga.com?Subject=Portfolio%20Interest") %></li>
              <li class="contact">
                <div class="contact-box">
                  <div class="contact-icon twilio"><%= fa_icon("phone") %></div>
                  <div class="contact-under twilio">Twilio</div>
              </li>
              <!--<li class="contact">(906)662-4859</li>-->
            </ul>
        </div>
        <div class="twilio-box">
          <span class="twilio-close"><%= fa_icon("times") %></span>
          <span class="twilio-number">(906) 662-4859</span>
          <span class="twilio-power">Powered by Twilio API</span>
        </div>

        <div class="stripe-box">
          <div class="stripe-close"><%= fa_icon("times") %></div>
          <div class="stripe-header">Donate to WUP Rise / 4 the Kids</div>
          <div class="stripe-note">To be clear, this is live. Its NOT a demo.<br />But does demonstrate my use of Stripe and Twilio API.</div>
          <div class="donate-intro">
            <p>I, Peter, am a founding member of WUP Rise / 4 the Kids. We are a U.S. Non-profit organization that raises money to support the youth of the Western Upper Peninsula of Michigan. We are primarily interested
            in helping in the areas of technology education, fitness and athletics. Information about our most recent project can be found <a class="stripe-link" target="_blank"href='https://www.facebook.com/4thekidswakefield'>here</a>.</p>
            <p>If you have any questions please feel free to contact me anytime.</p>
            <p>To donate, please fill out the form below.</p>
          </div>
          <%= form_tag('/donate', method: :post, id: "payment-form")%>
              <table>
                <tr>
                  <th><%= label_tag(:firstname, 'First Name') %></th>
                  <td><%= text_field_tag(:firstname, nil, class: 'big-field')%></td>
                </tr>
                <tr>
                  <th><%= label_tag(:lastname, 'Last Name') %></th>
                  <td><%= text_field_tag(:lastname, nil, class: 'big-field')%></td>
                </tr>
                <tr>
                  <th><%= label_tag(:company, 'Company') %></th>
                  <td><%= text_field_tag(:company, nil, class: 'big-field')%></td>
                </tr>
                <tr>
                  <th><%= label_tag(:email) %></th>
                  <td><%= text_field_tag(:email, nil, class: 'big-field')%></td>
                </tr>
                <tr>
                  <th><%= label_tag(:amount, 'Amount in US$') %></th>
                  <td><%= text_field_tag(:amount, nil, class: 'big-field')%></td>
                </tr>
                <tr>
                  <th></th>
                  <td></td>
                </tr>
              </table>
                <div class="card-info">
                  <%= label_tag('card-element', 'Card Info') %>
                  <div id="card-element"></div>
                </div>
                <div id="card-errors" role="alert"></div>

              <button>Submit Donation</button>
            
            </form>
        </div>

    </div>
    <%= yield %>
    <footer>
      <div class="footer">Admittedly not a designer. But theme is based on my love of sunrise and sunset.</div>
    </footer>
  </body>
</html>

rails/peter/app/views/layouts/resume.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "resume_print" -%>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

rails/peter/app/views/projects/delete.html.erb
<h1>Delete <%= @project.title %></h1>
<%= link_to("Back to page", project_path(@project.id))%>
<%= form_for(@project, :method => 'delete') do |f| %>

    <p>Are you sure that you want to delete the project: <%= f.object.title %>?</p>
    <div class="form-buttons">
        <%= f.submit("Delete #{@project.title}") %>
    </div>
<% end %>

rails/peter/app/views/projects/edit.html.erb
<h1>Edit <%= @project.title%></h1>
<br />
<%= link_to 'Back', project_path(@project)%>
<%= form_for(@project) do |f| %>
    <%= hidden_field_tag(:from, @from, :readonly => true) %>
    <table summary="Project form fields">
        <tr>
            <th>Title</th>
            <td><%= f.text_field(:title) %></td>
        </tr>
        <tr>
            <th>Intro</th>
            <td><%= f.text_field(:intro) %></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><%= f.text_area(:description) %></td>
        </tr>
        <tr>
            <th>Tech</th>
            <td><%= f.collection_check_boxes( :tech_ids, Tech.all, :id, :name) %></td>
        </tr>
        <tr>
            <th>Public URL</th>
            <td><%= f.text_field(:publicUrl) %></td>
        </tr>
        <tr>
            <th>Admin URL</th>
            <td><%= f.text_field(:adminUrl) %></td>
        </tr>
        <tr>
            <th>Github URL</th>
            <td><%= f.text_field(:gitUrl) %></td>
        </tr>
        <tr>
            <th>Main Image</th>
            <td><%= f.file_field(:main_image) %></td>
        </tr>
        <tr>
            <th>Other Images</th>
            <td><%= f.file_field(:image, multiple: true ) %></td>
        </tr>
    </table>
    <div class="form-buttons">
        <%= f.submit("Edit #{@project.title}") %>
    </div>
<% end %>

rails/peter/app/views/projects/index.html.erb
<h1>Projects</h1>
<%= link_to('New', new_project_path())%>
<div class="admin-projects">
    <div class="project-list">
        <% @projects.each do |project| %>
            <% if project = @default %>
                <div class='project-title selected'><%= link_to(project.title, project_path(project.id)) %></div>
            <% else %>
                <div class='project-title'><%= link_to(project.title, project_path(project.id)) %></div>
            <% end %>
        <% end %>
    </div>
    <div class='admin-project'>
            <div class='project-title'><%= link_to(project.title, project_path(project.id)) %></div>
            <div class="project-tech">
                <% project.teches.each do |tech| %>
                    <div class="tech-item"><%= tech.name %></div>
                <% end %>
            </div>
            <%= link_to('Edit', edit_project_path(id: project.id, from: 'i'))%>
    </div>
</div>

rails/peter/app/views/projects/show.html.erb
<div class="admin-projects">
    <div class="admin-top">
        <div class="admin-head-page-title">Admin Area</div>
        <div class="admin-menu"><%= @user ? link_to("Logout #{@user.first_name}" , access_logout_path()) : link_to('Login', access_login_path()) %></div>
    </div>
    <div class="project-list">
        <div class="admin-menu-title">Projects</div>
        <% @allProjects.each do |project| %>
            <% if project.id == @project.id%>
                <div class='project-title selected'><%= link_to(project.title, project_path(project.id)) %></div>
            <% else %>
                <div class='project-title'><%= link_to(project.title, project_path(project.id)) %></div>
            <% end %>
        <% end %>
    </div>
    <div class='admin-project'>
        <%= form_for(@project, method: :put) do |f| %>
            <%= hidden_field_tag(:from, @from, :readonly => true) %>

            <div class="project-form-fields">
                <%= content_tag(:div, f.text_field(:title, class: ["form-input", "form-title"], placeholder: "Title"), class: "form-item") %>
                <%= content_tag(:div, f.text_field(:intro, class: ["form-input", "form-intro"], placeholder: "Short Intro"), class: "form-item") %>
                <%= content_tag(:div, f.text_area(:description, class: ["form-input", "form-description"], placeholder: "Full Description"), class: "form-item") %>
                <%= content_tag(:div, f.collection_check_boxes( :tech_ids, Tech.all, :id, :name, class: ["form-input", "form-description"]), class: ["form-tech", "form-item"]) %>
                <%= content_tag(:div, f.text_field(:publicUrl, class: ["form-input", "form-public"], placeholder: "Public URL"), class: "form-item") %>
                <%= content_tag(:div, f.text_field(:adminUrl, class: ["form-input", "form-admin"], placeholder: "Admin URL"), class: "form-item") %>
                <%= content_tag(:div, f.text_field(:gitUrl, class: ["form-input", "form-git"], placeholder: "Github URL"), class: "form-item") %>
                <div class="form-item form-main image">

                </div>
                <div class="form-item form-image image">
                    <div class="form-image-con">
                        <div class="form-image-label">Main Image</div>
                        <div class="form-image-field"><%= f.file_field(:main_image) %></div>
                    </div>
                    <div class="form-main-image">
                        <% if @project.main_image.attached? %>
                            <%= image_tag(@project.main_image, class: "list-item-image")%>
                        <% end %>
                    </div>
                </div>
                <div class="form-item form-image image">
                    <div class="form-image-con">
                        <div class="form-image-label">Other Images</div>
                        <div class="form-image-field"><%= f.file_field(:image, multiple: true ) %></div>
                    </div>
                    <div class="form-main-image">
                        <% @project.image.each do |i| %>
                            <%= content_tag(:div, image_tag(i, class: "list-item-image"), class: "list-item" )%>
                        <% end %>
                    </div>
                </div>
                <div class="form-buttons">
                <%= f.submit("Edit #{@project.title}") %>
                <%= link_to('Delete', delete_project_path(@project.id)) %>
            </div>
            </div>
        <% end %>     
    </div>
</div>